### ISSUE TITLE
should get first 100 rows

### ISSUE THREAD

**Issue by ad3429** [mtkaufman/sql-scratch-capstone-turn-in#1]
https://github.com/mtkaufman/sql-scratch-capstone-turn-in/blob/master/Matthew_Kaufma_Code_Acadamey_Learn_SQL_from_Scratch_01082019/code.sql#L5

Step 1 asks to get the first 100 rows. Therefore, this should be LIMIT 100 instead of LIMIT 20.

**Comment by mtkaufman** [comment]
Oops-sorry! I had 100 when I initially did it then shortened it for the powerpoint. Not useful though
