### ISSUE TITLE
step 4 can be simplified

### ISSUE THREAD

**Issue by ad3429** [mtkaufman/sql-scratch-capstone-turn-in#2]
For step 4, you should just be able to do something like:

```
cross_join AS (
  SELECT * 
  FROM subscriptions
  CROSS JOIN months
),
```

**Comment by mtkaufman** [comment]
My code is below-you're saying that I didn't need the first part before the cross_join?

WITH months AS
 (SELECT '2017-01-01' AS 'first_day',
 '2017-01-31' AS 'last_day'
 UNION
 SELECT '2017-02-01' AS 'first_day',
 '2017-02-28' AS 'last_day'
 UNION
 SELECT '2017-03-01' AS 'first_day',
 '2017-03-31' AS 'last_day'),
 cross_join AS
 (SELECT *
 FROM subscriptions
 CROSS JOIN months)
 SELECT *
 FROM cross_join
 LIMIT 100;
