### ISSUE TITLE
query formatting

### ISSUE THREAD

**Issue by ad3429** [mtkaufman/sql-scratch-capstone-turn-in#3]
Your queries can be formatted better for more readability. For example, for step 3 a well formatted query would look like:

```
 WITH months AS (
  SELECT 
    '2017-01-01' AS first_day, 
    '2017-01-31' AS last_day 
  UNION 
  SELECT 
    '2017-02-01' AS first_day, 
    '2017-02-28' AS last_day 
  UNION 
  SELECT 
    '2017-03-01' AS first_day, 
    '2017-03-31' AS last_day
),
```

Refer to this style guide if you want to learn more about formatting:

https://s3.amazonaws.com/codecademy-content/programs/learn-sql-from-scratch/SQL+Style+Guide+for+Learn+SQL+from+Scratch.pdf

Here is another great style guide:

https://www.sqlstyle.guide/

**Comment by mtkaufman** [comment]
OK-noted
