### ISSUE TITLE
Churn Rates with Codeflix (SQL) Summary 

### ISSUE THREAD

**Issue by ad3429** [mtkaufman/sql-scratch-capstone-turn-in#5]
**Rubric Score**

**Criteria 1: Report**
- Score Level: 4/4

- Comment(s): Your conclusions are clear and related queries are properly attached in your sql file to support your findings. Good job! 

**Criteria 2: Query Accuracy**

- Score Level: 4/4

- Comment(s): All queries accurately retrieve the data intended. Some of your queries can be simplified, as noted in the Issues section above. 

**Criteria 3: Query Formatting**

- Score Level: 3/4

- Comment(s): Queries adhere to the rules for the most part, but at times your queries are difficult to read and can be formatted better. Here are great resources to utilize to learn more about query styling/formatting:

https://s3.amazonaws.com/codecademy-content/programs/learn-sql-from-scratch/SQL+Style+Guide+for+Learn+SQL+from+Scratch.pdf

https://www.sqlstyle.guide/

**Criteria 4: Understanding underlying concepts and terminology**

- Score Level: 4/4

- Comment(s): Great job, it's clear you have a good conceptual grasp of the concepts. 

**Overall Score: 15/16**

Overall, great job! It's very clear that you have a solid understanding of SQL, and it will only get better as you progress with more projects. Make sure to spend more time formatting/styling your queries, as its very important that your SQL has good readability. You can utilize the resources I linked above for that. Keep up the great work!

**Comment by mtkaufman** [comment]
Thanks!!
